### ISSUE TITLE
【ゲーム画面】問題が更新されない。

### ISSUE THREAD

**Issue by kngmed** [stecan/Quiz-App#19]
ボタンを追加して
ボタン押下時に情報取得

**Comment by suzaki-kana** [comment]
自動でリクエストを投げていたかったが、通信量の都合を考慮して一旦マニュアル（ボタン）対応としてほしい。。

**Comment by suzaki-kana** [comment]
問題・解答・回答者のコンポーネントに対し「表示更新」ボタンを追加しました。
