### ISSUE TITLE
【手札選択画面】クライアント処理実装

### ISSUE THREAD

**Issue by kngmed** [stecan/Quiz-App#6]
手札取得：get  20枚の手札を取得する。取得する手札はログインフラグがたっているレコード。
手札確定：post　画面表示した手札の確定を行う。

**Comment by suzaki-kana** [comment]
apiで実装済み。
呼び出しは↓のとおり。
`axios.get('/api/axios/drawingcard'{my_user_id='ログインユーザID'}).then(res =>{//res.data})`
res.dataの中身がm_userのid,user_id,user_name,departmentの配列で戻る
