### ISSUE TITLE
【集計画面】画面実装

### ISSUE THREAD

**Issue by kngmed** [stecan/Quiz-App#7]
ランキング1~〇〇位までのユーザーを表示する。

**Comment by suzaki-kana** [comment]
ダイアログとして作成完了。
画面への組み込み方
`<ranking-dialog :dialog="dispRanking" :rankings="ranking"></ranking-dialog>`
dispRanking：boolean　trueで表示
ranking：array　/api/axios/getranking での戻り値を渡す

運営画面へは組み込み済みなので参考にしてください。
